sylius_resource:
    resources:
        app.supplier:
            classes:
                model: AppBundle\Entity\Supplier
        app.automailer:
            classes:
                model: AppBundle\Entity\Automailer
