sylius_grid:
    grids:
        app_admin_supplier:
            driver:
                name: doctrine/orm
                options:
                    class: AppBundle\Entity\Supplier
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                code:
                    type: string
                    label: sylius.ui.code
                state:
                    type: string
                    label: sylius.ui.state
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                    trust:
                        type: apply_transition
                        label: app.ui.trust
                        icon: checkmark
                        options:
                            link:
                                route: app_admin_supplier_trust
                                parameters:
                                    id: resource.id
                            class: green
                            transition: trust
                            graph: app_supplier
        app_admin_automailer:
                    driver:
                        name: doctrine/orm
                        options:
                            class: AppBundle\Entity\Automailer
                    fields:
                        fromEmail:
                            type: string
                        toEmail:
                            type: string
                    actions:
                        main:
                            create:
                                type: create
                        item:
                            update:
                                type: update
                            delete:
                                type: delete