winzou_state_machine:
    app_supplier:
        class: '%app.model.supplier.class%'
        property_path: 'state'
        graph: app_supplier
        state_machine_class: '%sylius.state_machine.class%'
        states:
            new: ~
            trusted: ~
            gold: ~
        transitions:
            trust:
                from: [new]
                to: trusted
            goldify:
                from: [trusted]
                to: gold
        callbacks:
            after:
                send_supplier_email:
                    on: 'trust'
                    do: ['@app.sender.trust_supplier_email', 'sendTrustEmail']
                    args: ['object']
