services:
    app.sender.trust_supplier_email:
        class: AppBundle\Sender\TrustSupplierEmailSender
        arguments: ['@sylius.email_sender']

    app.order_processor.heavy_order:
        class: AppBundle\OrderProcessor\HeavyOrderProcessor
        arguments: ['@sylius.factory.adjustment']
        tags:
            - { name: sylius.order_processor, priority: 0 }

    sylius.order_processing.order_adjustments_clearer:
        class: AppBundle\OrderProcessor\OrderAdjustmentsClearer
        tags:
            - { name: sylius.order_processor, priority: 1024 }

    app.provider.fake_tax_number_provider:
        class: AppBundle\Provider\FakeTaxNumberProvider

    app.assigner.customer_tax_number_assigner:
        class: AppBundle\Assigner\CustomerTaxNumberAssigner
        arguments:
            - "@app.provider.fake_tax_number_provider"
            - "@sylius.repository.customers"

    app.form.extension.customer:
        class: AppBundle\Form\Extension\CustomerTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CustomerBundle\Form\Type\CustomerType }
