AppBundle\Entity\Customer:
    type: entity
    table: sylius_customer
    fields:
        taxNumber:
            type: string
            column_name: tax_number
            nullable: true
            unique: true
