app_supplier:
    resource: |
        alias: app.supplier
        except: ['show']
        templates: SyliusAdminBundle:Crud
        section: admin
        grid: app_admin_supplier
    type: sylius.resource

app_admin_supplier_trust:
    path: /suppliers/{id}/trust
    methods: [PUT]
    defaults:
        _controller: app.controller.supplier:applyStateMachineTransitionAction
        _sylius:
            state_machine:
                graph: app_supplier
                transition: trust
            redirect: referer
            flash: app.supplier.trust
